### ISSUE TITLE
Minimilize JSON return data

### ISSUE THREAD

**Issue by ghost** [pamaxie/Pamaxie.Database#6]
We should minimize the JSON return data for most Endpoints to not include objects that are null (completely remove them) or lists that are empty. This saves some network traffic and in general just will save us some performance.

Example:
Don't do this:
`{
    "Id": 963460958875815936,
    "Email": "john@doe.mail",
    "UserName": "JohnDoe",
    "LastName": "John",
    "FirstName": "Doe",
    "PasswordHash": null,
    "KnownIps": [
        "192.168.1.1"
    ],
    "Projects": [],
    "Flags": 18,
    "CreationDate": "2022-04-12T15:34:31.300681Z",
    "TTL": "2022-09-05T11:17:50.155621Z"
}`

Do this:
`{
    "Id": 963460958875815936,
    "Email": "john@doe.mail",
    "UserName": "JohnDoe",
    "LastName": "John",
    "FirstName": "Doe",
    "KnownIps": [
        "192.168.1.1"
    ],
    "Flags": 18,
    "CreationDate": "2022-04-12T15:34:31.300681Z",
    "TTL": "2022-09-05T11:17:50.155621Z"
}`

**Comment by Ali-Kabbadj** [comment]
Hey there , i haven't looked at the code source and the structure of the project yet , but i would suggest to use DTO pattern and some kind of mapping (AutoMapper as an example) to have more control over the flow of the entities .
Let me know what you think  . either way i would like to woke on this
